#!/usr/bin/env php
<?php
use Command\ConsoleCommand;
use Command\ModelGeneratorCommand;
use Command\RoutesCommand;
use Ouzo\Utilities\Files;
use Symfony\Component\Console\Application;

putenv('environment=prod');

define('ROOT_PATH', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR);

require 'vendor/autoload.php';

Files::loadIfExists(ROOT_PATH . 'test/Application/config/routes.php');

$app = new Application();
$app->add(new ConsoleCommand());
$app->add(new RoutesCommand());
$app->add(new ModelGeneratorCommand());
$app->run();