#!/usr/bin/env php
<?php
use Ouzo\Console\CommandsLoader;
use Ouzo\Injection\Injector;
use Ouzo\Utilities\Files;
use Ouzo\Utilities\Path;
use Symfony\Component\Console\Application;

putenv('environment=prod');

define('ROOT_PATH', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR);

require 'vendor/autoload.php';

Files::loadIfExists(ROOT_PATH . 'test/Application/config/routes.php');

$app = new Application();
CommandsLoader::forApplicationAndInjector($app, new Injector())
    ->registerCommandsFromPath(Path::join(ROOT_PATH, "bin"), "\\Command");
$app->run();
