<?
if (\Ouzo\Config::load()->getConfig('debug')) {
    ?>
    <div style="clear: both; padding: 50px; border: 1px; background-color: #ffffee; color: #000000">
        <a href="#stats" onclick="reloadStats()">Click to refresh</a>

        <h2>STATISTICS</h2>

        <div id="stats"></div>
    </div>
    <script>
        var url = "<?= url(array('controller' => 'stats', 'action' => 'show')) ?>";

        function reloadStats() {
            $.get(url, function (data) {
                $('#stats').html(data);
            });
        }
        reloadStats();
    </script>
<?
}
?>