<meta charset="utf-8"/>
<style>
    body {
        margin: 0;
        padding: 10px;
    }

    #errorTrace {
        margin: 0;
        font-size: 16px;
        border: 2px solid;
        background-color: #FF9999;
        padding: 10px;
    }

    #message {
        margin: 0;
    }

    #trace {
        margin-top: 10px;
    }

    pre {
        font-size: 12px;
        overflow: auto;
        width: 95%
    }
</style>
<? if (\Ouzo\Config::load()->getConfig('debug')): ?>
    <div id="errorTrace">
        <p id="message">Message: <strong><?php echo $errorMessage; ?></strong></p>
        <hr/>
        <div id="trace"> Error ID: <?= \Ouzo\FrontController::$requestId ?> </div>
        <hr/>
        <div id="trace">
            Trace:
        <pre>
        <?php echo trim($errorTrace); ?>
        </pre>
        </div>
    </div>
<? else: ?>
    <div id="errorTrace">
        <p id="message"><strong>Wystąpił błąd. Skopiuj poniższy identyfikator błędu (ID) i skontaktuj się z nami.</strong>
        </p>
        <hr/>
        <div id="trace">ID: <?= \Ouzo\FrontController::$requestId ?></div>
    </div>
<? endif; ?>